# Generated by Django 2.1.7 on 2019-10-06 08:28

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('userId', models.IntegerField()),
                ('twitterId', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('oauth_token', models.CharField(max_length=100)),
                ('oauth_token_secret', models.CharField(max_length=100)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
